SmartAccountsUI/Models/ViewModels/Invoicing/CustomerViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace SmartAccountsUI.Models.ViewModels.Invoicing
{
    public class CustomerViewModel
    {
        public CustomerViewModel()
        {
            CustomerAllocations = new HashSet<CustomerAllocation>();
            CustomerInvoices = new HashSet<CustomerInvoicingInvoice>();
        }

        public long Id { get; set; }
        public string Name { get; set; }
        public decimal Balance { get; set; }

        public virtual ICollection<CustomerAllocation> CustomerAllocations { get; set; }
        public virtual ICollection<CustomerInvoicingInvoice> CustomerInvoices { get; set; }
    }
}

SmartAccountsUI/Models/ViewModels/Invoicing/Customers.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SmartAccountsUI.Models.ViewModels.Invoicing
{
    public class Customers
    {
        public Customers()
        {
            CustomerListLines = new HashSet<CustomerListLine>();
        }

        public ICollection<CustomerListLine> CustomerListLines { get; set; }
    }

    public class CustomerListLine
    {
        public long Id { get; set; }
        public string Name { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public decimal Balance { get; set; }
    }

    public class CustomerDetail
    {
        public CustomerDetail()
        {
            CustomerAllocations = new HashSet<CustomerAllocation>();
            CustomerInvoices = new HashSet<CustomerInvoicingInvoice>();
            ActualAllocations = new HashSet<Allocations>();
        }

        public long Id { get; set; }
        public string Name { get; set; }
        public decimal Balance { get; set; }

        public virtual ICollection<CustomerAllocation> CustomerAllocations { get; set; }
        public virtual ICollection<CustomerInvoicingInvoice> CustomerInvoices { get; set; }
        public ICollection<Allocations> ActualAllocations { get; set; }
    }

    public class CustomerReceipt
    {

    }

    public class CustomerInvoicingInvoice
    {
        public long Id { get; set; }
        public DateTime Date { get; set; }
        public string InvoiceNo { get; set; }
        public decimal Amount { get; set; }
        public string Status { get; set; }
    }

    public class CustomerInvoicingOrder
    {

    }

    public class CustomerAllocation
    {
        public long Id { get; set; }
        public decimal AmountAllocated { get; set; }
        public decimal AvailableAmountToAllocate { get; set; }
    }

    public class Allocations
    {
        public string InvoiceNo { get; set; }
        public string ReceiptNo { get; set; }
        public DateTime Date { get; set; }
        public decimal Amount { get; set; }
    }

    public class Allocate
    {
        public Allocate()
        {
            OpenInvoices = new HashSet<SelectListItem>();
        }

        public long ReceiptId { get; set; }
        public long InvoiceId { get; set; }
        public string InvoiceNo { get; set; }
        public decimal AmountToAllocate { get; set; }
        public decimal InvoiceAmount { get; set; }
        public decimal TotalAmountAvailableToAllocate { get; set; }
        public decimal LeftToAllocateFromReceipt { get; set; }

        public ICollection<SelectListItem> OpenInvoices { get; set; }
    }

    public class EditCustomer
    {
        public EditCustomer()
        {
        }

        public long Id { get; set; }
        [Required]
        public string Name { get; set; }
        public long PrimaryContactId { get; set; }

        public long? AccountsReceivableSaAccountId { get; set; }
        public long? InvoicingSaAccountId { get; set; }
        public long? InvoicingDiscountSaAccountId { get; set; }
        public long? InvoicingPenaltySaAccountId { get; set; }
    }

    public class AddCustomer
    {
        public string Name { get; set; }
    }
}

SmartAccountsUI/Models/ViewModels/MasterTable/CustomerViewModel.cs
using System;
using System.Collections.Generic;

using System.Web.Mvc;

using System.ComponentModel.DataAnnotations;

namespace SmartAccountsUI.Models.ViewModels.MasterTable
{
    public class CustomerViewModel
    {
        public CustomerViewModel()
        {
            CustomerListLines = new HashSet<CustomerListLine>();
        }

        public ICollection<CustomerListLine> CustomerListLines { get; set; }
    }

    public class CustomerListLine
    {
        public long Id { get; set; }
        public string Name { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public decimal Balance { get; set; }
    }

    public class CustomerDetail
    {
        public CustomerDetail()
        {
            CustomerAllocations = new HashSet<CustomerAllocation>();
            CustomerInvoices = new HashSet<CustomerSalesInvoice>();
            ActualAllocations = new HashSet<Allocations>();
        }

        public long Id { get; set; }
        public string Name { get; set; }
        public decimal Balance { get; set; }

        public virtual ICollection<CustomerAllocation> CustomerAllocations { get; set; }
        public virtual ICollection<CustomerSalesInvoice> CustomerInvoices { get; set; }
        public ICollection<Allocations> ActualAllocations { get; set; }
    }

    public class CustomerReceipt
    {

    }

    public class CustomerSalesInvoice
    {
        public long Id { get; set; }
        public DateTime Date { get; set; }
        public string InvoiceNo { get; set; }
        public decimal Amount { get; set; }
        public string Status { get; set; }
    }

    public class CustomerSalesOrder
    {

    }

    public class CustomerAllocation
    {
        public long Id { get; set; }
        public decimal AmountAllocated { get; set; }
        public decimal AvailableAmountToAllocate { get; set; }
    }

    public class Allocations
    {
        public string InvoiceNo { get; set; }
        public string ReceiptNo { get; set; }
        public DateTime Date { get; set; }
        public decimal Amount { get; set; }
    }

    public class Allocate
    {
        public Allocate()
        {
            OpenInvoices = new HashSet<SelectListItem>();
        }

        public long ReceiptId { get; set; }
        public long InvoiceId { get; set; }
        public string InvoiceNo { get; set; }
        public decimal AmountToAllocate { get; set; }
        public decimal InvoiceAmount { get; set; }
        public decimal TotalAmountAvailableToAllocate { get; set; }
        public decimal LeftToAllocateFromReceipt { get; set; }

        public ICollection<SelectListItem> OpenInvoices { get; set; }
    }

    public class EditCustomer
    {
        public EditCustomer()
        {
        }

        public long Id { get; set; }
        [Required]
        public string Name { get; set; }
        public long PrimaryContactId { get; set; }

        public long? SaAccountsReceivableSaAccountId { get; set; }
        public long? InvoicingSaAccountId { get; set; }
        public long? InvoicingDiscountSaAccountId { get; set; }
        public long? AccountsReceivableSaAccountId { get; set; }
        public long? SalesSaAccountId { get; set; }
        public long? SalesDiscountSaAccountId { get; set; }
        public long? PromptPaymentDiscountSaAccountId { get; set; }
    }

    public class AddCustomer
    {
        public string Name { get; set; }
    }
}

SmartAccountsUI/Controllers/ReceivablesController.cs
using SAServices.Financial;
using SAServices.Inventory;
using SAServices.Receivables;
using System.Web.Mvc;
using System.Linq;
using SACore.Domain.Receivables;
using System.Collections.Generic;
using System;
using SACore.Domain;

namespace SmartAccountsUI.Controllers
{
    [Authorize]
    public class ReceivablesController : BaseController
    {
        private SmartAccountsUI.Models.ViewModels.Receivables.ReceivablesViewModelBuilder _viewModelBuilder;

        private readonly IInventoryService _inventoryService;
        private readonly IFinancialService _financialService;
        private readonly IInvoicingService _receivablesService;

        public ReceivablesController(IInventoryService inventoryService,
            IFinancialService financialService,
            IInvoicingService salesService)
        {
            _inventoryService = inventoryService;
            _financialService = financialService;
            _receivablesService = salesService;

            _viewModelBuilder = new SmartAccountsUI.Models.ViewModels.Receivables.ReceivablesViewModelBuilder(inventoryService, financialService, salesService);
        }

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult SalesOrders()
        {
            var salesOrders = _receivablesService.GetInvoicingOrders();
            var model = _viewModelBuilder.CreateSalesOrdersViewModel(salesOrders.ToList());
            return View(model);
        }

        public ActionResult SalesDeliveries()
        {
            var salesDeliveries = _receivablesService.GetInvoicingDeliveries();
            var model = _viewModelBuilder.CreateSalesDeliveriesViewModel(salesDeliveries.ToList());
            return View(model);
        }

        public ActionResult AddInvoicingDelivery(bool direct = false)
        {
            if (direct)
            {
                var model = _viewModelBuilder.CreateInvoicingDeliveryViewModel();
                return View(model);
            }
            return RedirectToAction("SalesDeliveries");
        }

        [HttpPost, ActionName("AddInvoicingDelivery")]
        [FormValueRequiredAttribute("SaveInvoicingDelivery")]
        public ActionResult SaveInvoicingDelivery(Models.ViewModels.Receivables.InvoicingDeliveryViewModel model)
        {
            var InvoicingDelivery = new InvoicingDeliveryHeader()
            {
                CustomerId = model.CustomerId,
                PaymentTermId = model.PaymentTermId,
                Date = model.Date,
                CreatedBy = User.Identity.Name,
                CreatedOn = DateTime.Now,
                ModifiedBy = User.Identity.Name,
                ModifiedOn = DateTime.Now,
            };
            foreach(var line in model.InvoicingDeliveryLines)
            {
                InvoicingDelivery.InvoicingDeliveryLines.Add(new InvoicingDeliveryLine()
                {
                    ItemId = line.ItemId,
                    MeasurementId = line.MeasurementId,
                    Quantity = line.Quantity,
                    Discount = line.Discount,
                    Price = line.Quantity * line.Price,
                    CreatedBy = User.Identity.Name,
                    CreatedOn = DateTime.Now,
                    ModifiedBy = User.Identity.Name,
                    ModifiedOn = DateTime.Now,
                });
            }
            _receivablesService.AddInvoicingDelivery(InvoicingDelivery, true);
            return RedirectToAction("SalesDeliveries");
        }

        [HttpPost, ActionName("AddInvoicingDelivery")]
        [FormValueRequiredAttribute("AddInvoicingDeliveryLineItem")]
        public ActionResult AddInvoicingDeliveryLineItem(Models.ViewModels.Receivables.InvoicingDeliveryViewModel model)
        {
            var item = _inventoryService.GetItemById(model.ItemId.Value);
            var line = new Models.ViewModels.Receivables.InvoicingDeliveryLineViewModel()
            {
                ItemId = model.ItemId,
                MeasurementId = model.MeasurementId,
                Quantity = model.Quantity,
                Price = item.Price.Value * model.Quantity,
                Discount  = model.Discount,
                LineTotalTaxAmount = item.ItemTaxAmountOutput * model.Quantity
            };

            model.InvoicingDeliveryLines.Add(line);
            return View(model);
        }

        [HttpPost, ActionName("AddInvoicingDelivery")]
        [FormValueRequiredAttribute("DeleteSaleDeliveryLineItem")]
        public ActionResult DeleteSaleDeliveryLineItem(Models.ViewModels.Receivables.InvoicingDeliveryViewModel model)
        {
            var request = HttpContext.Request;
            var deletedItem = request.Form["DeletedLineItem"];
            model.InvoicingDeliveryLines.Remove(model.InvoicingDeliveryLines.Where(i => i.ItemId == int.Parse(deletedItem.ToString())).FirstOrDefault());
            return View(model);
        }

        public ActionResult SalesInvoices()
        {
            var invoices = _receivablesService.GetInvoicingInvoices();
            var model = new SmartAccountsUI.Models.ViewModels.Receivables.SalesInvoices();
            foreach(var invoice in invoices)
            {
                model.SalesInvoiceListLines.Add(new Models.ViewModels.Receivables.SalesInvoiceListLine()
                {
                    Id = invoice.Id,
                    No = invoice.No,
                    Customer = invoice.Customer.Name,
                    Date = invoice.Date,
                    Amount = invoice.ComputeTotalAmount(),
                    IsFullPaid = invoice.IsFullPaid()
                });
            }
            return View(model);
        }

        public ActionResult AddSalesInvoice(bool direct = false)
        {
            var model = new SmartAccountsUI.Models.ViewModels.Receivables.AddSalesInvoice();
            model.Customers = Models.ModelViewHelper.Customers(_receivablesService.GetCustomers());
            model.Items = Models.ModelViewHelper.Items(_inventoryService.GetAllItems());
            model.Measurements = Models.ModelViewHelper.Measurements(_inventoryService.GetMeasurements());

            return View(model);
        }

        [HttpPost, ActionName("AddSalesInvoice")]
        [FormValueRequiredAttribute("SaveSalesInvoice")]
        public ActionResult SaveSalesInvoice(Models.ViewModels.Receivables.AddSalesInvoice model)
        {
            if (model.AddSalesInvoiceLines.Sum(i => i.Amount) == 0 || model.AddSalesInvoiceLines.Count < 1)
            {
                model.Customers = Models.ModelViewHelper.Customers(_receivablesService.GetCustomers());
                model.Items = Models.ModelViewHelper.Items(_inventoryService.GetAllItems());
                model.Measurements = Models.ModelViewHelper.Measurements(_inventoryService.GetMeasurements());
                ModelState.AddModelError("Amount", "No invoice line");
                return View(model);
            }
            var invoiceHeader = new InvoicingInvoiceHeader();
            var invoiceLines = new List<InvoicingInvoiceLine>();
            foreach (var item in model.AddSalesInvoiceLines)
            {
                var Item = _inventoryService.GetItemById(item.ItemId);
                var invoiceDetail = new InvoicingInvoiceLine();
                invoiceDetail.TaxId = Item.ItemTaxGroupId;
                invoiceDetail.ItemId = item.ItemId;
                invoiceDetail.MeasurementId = item.MeasurementId;
                invoiceDetail.Quantity = item.Quantity;
                invoiceDetail.Discount = item.Discount;
                invoiceDetail.Amount = Convert.ToDecimal(item.Quantity * Item.Price);
                invoiceDetail.CreatedBy = User.Identity.Name;
                invoiceDetail.CreatedOn = DateTime.Now;
                invoiceDetail.ModifiedBy = User.Identity.Name;
                invoiceDetail.ModifiedOn = DateTime.Now;
                invoiceLines.Add(invoiceDetail);
            }
            invoiceHeader.InvoicingInvoiceLines = invoiceLines;
            invoiceHeader.CustomerId = model.CustomerId;
            invoiceHeader.Date = model.Date;
            invoiceHeader.ShippingHandlingCharge = 4;// model.ShippingHandlingCharge;
            invoiceHeader.CreatedBy = User.Identity.Name;
            invoiceHeader.CreatedOn = DateTime.Now;
            invoiceHeader.ModifiedBy = User.Identity.Name;
            invoiceHeader.ModifiedOn = DateTime.Now;

            _receivablesService.AddInvoicingInvoice(invoiceHeader, model.SalesOrderId);
            return RedirectToAction("SalesInvoices");
        }

        [HttpPost, ActionName("AddSalesInvoice")]
        [FormValueRequiredAttribute("AddSalesInvoiceLine")]
        public ActionResult AddSalesInvoiceLine(Models.ViewModels.Receivables.AddSalesInvoice model)
        {
            model.Customers = Models.ModelViewHelper.Customers(_receivablesService.GetCustomers());
            model.Items = Models.ModelViewHelper.Items(_inventoryService.GetAllItems());
            model.Measurements = Models.ModelViewHelper.Measurements(_inventoryService.GetMeasurements());
            if (model.Quantity > 0)
            {
                var item = _inventoryService.GetItemById(model.ItemId);
                if (!item.Price.HasValue)
                {
                    ModelState.AddModelError("Amount", "Selling price is not set.");
                    return View(model);
                }
                Models.ViewModels.Receivables.AddSalesInvoiceLine itemModel = new Models.ViewModels.Receivables.AddSalesInvoiceLine()
                {
                    ItemId = model.ItemId,
                    MeasurementId = model.MeasurementId,
                    Quantity = model.Quantity,
                    Discount = model.Discount,
                    Amount = item.Price.Value * model.Quantity,
                    Price = item.Price.Value,
                };

SmartAccountsUI/Views/Receivables/AddCustomer.cshtml
@model SmartAccountsUI.Models.ViewModels.Receivables.AddCustomer
@{
    ViewBag.Title = "AddCustomer";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using (Html.BeginForm())
{
    <div class="form-group">
        <label class="control-label">Name</label>
        @Html.TextBoxFor(m => m.Name)
    </div>
    <div class="form-group">
        <input type="submit" value="Save" name="SaveCustomer" />
    </div>
}

SmartAccountsUI/Views/Receivables/AddSalesInvoice.cshtml
@model SmartAccountsUI.Models.ViewModels.Receivables.AddSalesInvoice
@{
    ViewBag.Title = "AddSalesInvoice";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Add Sales Invoice</h2>

@using (Html.BeginForm())
{
    @Html.HiddenFor(m => m.SalesOrderId)
    <div>
        <div class="form-group">
            @Html.LabelFor(m => m.CustomerId, new { @class = "col-md-2 control-label" })
            @Html.DropDownListFor(m => m.CustomerId, Model.Customers)
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.Date, new { @class = "col-md-2 control-label" })
            @Html.EditorFor(m => m.Date)
        </div>
    </div>
    <table class="table">
        <thead>
            <tr>
                <th class="col-md-3">Item Code</th>
                <th class="col-md-3">Unit</th>
                <th class="col-md-3">Price</th>
                <th class="col-md-3">Quantity</th>
                <th class="col-md-3">Discount</th>
                <th class="col-md-3"></th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>@Html.DropDownListFor(m => m.ItemId, Model.Items)</td>
                <td>@Html.DropDownListFor(m => m.MeasurementId, Model.Measurements)</td>
                <td></td>
                <td>@Html.TextBoxFor(m => m.Quantity)</td>
                <td>@Html.TextBoxFor(m => m.Discount, new { @disabled = "disabled" })</td>
                <td>
                    <input type="submit" value="Add Item" name="AddSalesInvoiceLine" />
                </td>
            </tr>
            @if (Model != null)
            {
                for (int i = 0; i < Model.AddSalesInvoiceLines.Count; i++)
                {
                    @Html.HiddenFor(x => Model.AddSalesInvoiceLines[i].Amount)
                    <tr>
                        <td>
                            @Html.DisplayFor(x => Model.AddSalesInvoiceLines[i].ItemId)
                            @Html.HiddenFor(x => Model.AddSalesInvoiceLines[i].ItemId)
                        </td>
                        <td>
                            @Html.DisplayFor(x => Model.AddSalesInvoiceLines[i].MeasurementId)
                            @Html.HiddenFor(x => Model.AddSalesInvoiceLines[i].MeasurementId)
                        </td>
                        <td>
                            @Html.DisplayFor(x => Model.AddSalesInvoiceLines[i].Price)
                            @Html.HiddenFor(x => Model.AddSalesInvoiceLines[i].Price)
                        </td>
                        <td>
                            @Html.DisplayFor(x => Model.AddSalesInvoiceLines[i].Quantity)
                            @Html.HiddenFor(x => Model.AddSalesInvoiceLines[i].Quantity)
                        </td>
                        <td>
                            @Html.DisplayFor(x => Model.AddSalesInvoiceLines[i].Discount)
                            @Html.HiddenFor(x => Model.AddSalesInvoiceLines[i].Discount)
                        </td>
                        <td>
                            <input type="submit" value="Delete" name="DeleteInvoiceLineItem" id="@Model.AddSalesInvoiceLines[i].ItemId" onclick="return DeleteLineItem($(this).attr('id'));" />
                        </td>
                    </tr>
                }
            }
        </tbody>
        <tfoot>
            <tr>
                <td colspan="5" style="text-align: right;">Total Amount: @Model.AddSalesInvoiceLines.Sum(m => m.Amount)</td>
                <td></td>
            </tr>
        </tfoot>
    </table>
    <input type="hidden" value="" name="DeletedLineItem" />
    <div>
        <input type="submit" value="Save" name="SaveSalesInvoice" />
    </div>
}
<script type="text/javascript">
    function DeleteLineItem(id) {
        $('input[name="DeletedLineItem"]').val(id);
    }
</script>

SmartAccountsUI/Views/Receivables/AddSalesReceipt.cshtml
@model SmartAccountsUI.Models.ViewModels.Receivables.AddSalesReceipt
@using SmartAccountsUI.Models;
@{
    ViewBag.Title = "AddSalesReceipt";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Add Sales Receipt</h2>

@using (Html.BeginForm())
{
    @Html.HiddenFor(m => m.SalesInvoiceId)
    @Html.HiddenFor(m => m.SalesInvoiceNo)
    @Html.HiddenFor(m => m.InvoiceDate)
    @Html.HiddenFor(m => m.CustomerId)
    <div class="panel panel-default">
        <div class="panel-body">
            <div class="form-group">
                @Html.LabelFor(m => m.SaAccountToDebitId, new { @class = "col-md-2 control-label" })
                @Html.DropDownListFor(m => m.SaAccountToDebitId, ModelViewHelper.Banks())
            </div>
            <div class="form-group">
                @Html.LabelFor(m => m.SalesInvoiceNo, new { @class = "col-md-2 control-label" })
                @Html.DisplayFor(m => m.SalesInvoiceNo)
            </div>
            <div class="form-group">
                @Html.LabelFor(m => m.InvoiceDate, new { @class = "col-md-2 control-label" })
                @Html.DisplayFor(m => m.InvoiceDate)
            </div>
            <div class="form-group">
                @Html.LabelFor(m => m.CustomerId, new { @class = "col-md-2 control-label" })
                @Html.DisplayFor(m => m.CustomerId)
            </div>
        </div>
    </div>
    <h3>Line Items</h3>
    <div class="panel panel-default">
        <div class="panel-body">
            <table class="table">
                <thead>
                    <tr>
                        <th>Item</th>
                        <th>Measurement</th>
                        <th>Qty</th>
                        <th>Discount</th>
                        <th>Amount</th>
                        <th>Amount to pay</th>
                    </tr>
                </thead>
                <tbody>
                    @for (int i = 0; i < Model.AddSalesReceiptLines.Count; i++)
                    {
                        @Html.HiddenFor(m => Model.AddSalesReceiptLines[i].SalesInvoiceLineId)
                        @Html.HiddenFor(m => Model.AddSalesReceiptLines[i].ItemId)
                        @Html.HiddenFor(m => Model.AddSalesReceiptLines[i].MeasurementId)
                        @Html.HiddenFor(m => Model.AddSalesReceiptLines[i].Quantity)
                        @Html.HiddenFor(m => Model.AddSalesReceiptLines[i].Discount)
                        @Html.HiddenFor(m => Model.AddSalesReceiptLines[i].Amount)
                        <tr>
                            <td>@Model.AddSalesReceiptLines[i].ItemId</td>
                            <td>@Model.AddSalesReceiptLines[i].MeasurementId</td>
                            <td>@Model.AddSalesReceiptLines[i].Quantity</td>
                            <td>@Model.AddSalesReceiptLines[i].Discount</td>
                            <td>@Model.AddSalesReceiptLines[i].Amount</td>
                            <td>@Html.TextBoxFor(m => Model.AddSalesReceiptLines[i].AmountToPay)</td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
    <div>
        <input type="submit" value="Save" name="SaveSalesReceipt" />
    </div>
}

SmartAccountsUI/Views/Receivables/Allocate.cshtml
@model SmartAccountsUI.Models.ViewModels.Receivables.Allocate
@{
    //ViewBag.Title = "Allocate";
    //Layout = "~/Views/Shared/_Layout.cshtml";
}

@*<h2>Allocate</h2>*@
@using (Html.BeginForm())
{
    @Html.HiddenFor(m => m.ReceiptId)
    <div class="form-group">
        <label class="col-md-8 control-label">Invoice</label>
        @Html.DropDownListFor(m => m.InvoiceId, Model.OpenInvoices)
    </div>
    @*<div class="form-group">
        <label class="col-md-8 control-label">Invoice No</label>
        @Html.TextBoxFor(m => m.InvoiceNo, new { @class = "control-field" })
    </div>*@
    <div class="form-group">
        <label class="col-md-8 control-label">Available Amount to Allocate</label>
        @Html.DisplayFor(m => m.TotalAmountAvailableToAllocate, new { @class = "control-field" })
    </div>
    <div class="form-group">
        <label class="col-md-8 control-label">Left to Allocate</label>
        @Html.DisplayFor(m => m.LeftToAllocateFromReceipt, new { @class = "control-field" })
    </div>
    <div class="form-group">
        <label class="col-md-8 control-label">Amount</label>
        @Html.TextBoxFor(m => m.AmountToAllocate, new { @class = "control-field" })
    </div>
    <div>
        <input type="submit" value="Save" name="SaveAllocation" />
    </div>
}

SmartAccountsUI/Views/Receivables/Customers.cshtml
@model SmartAccountsUI.Models.ViewModels.Receivables.Customers
@{
    ViewBag.Title = "Customers";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Customers</h2>

@Html.ActionLink("Add Customer", "AddOrEditCustomer", "Receivables")
<table class="table">
    <thead>
        <tr>
            <th>Name</th>
            <th>Balance</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var customer in Model.CustomerListLines)
        {
            <tr>
                <td>@Html.ActionLink((string)string.Format("{0}", customer.Name), "CustomerDetail", new { id = customer.Id })</td>
                <td>@customer.Balance</td>
            </tr>
        }
    </tbody>
</table>

SmartAccountsUI/Views/Receivables/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div>
    <h2>Transactions</h2>
    <ul>
        <li>@Html.ActionLink("Direct Delivery", "AddSalesDelivery", new { direct = true })</li>
        <li>@Html.ActionLink("Direct Invoice", "AddSalesInvoice", new { direct = true })</li>
        <li>@Html.ActionLink("Delivery Against Sales Order", "AddSalesDelivery", new { direct = true })</li>
        <li>@Html.ActionLink("Invoice Against Sales Delivery", "AddSalesInvoice", new { direct = false })</li>
    </ul>
</div>
<div>
    <h2>Maintenance</h2>
</div>

SmartAccountsUI/Views/Receivables/Receipts.cshtml
@model SmartAccountsUI.Models.ViewModels.Receivables.SalesReceipts
@{
    ViewBag.Title = "Receipts";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Receipts</h2>
@Html.ActionLink("Add Receipt", "AddReceipt", "Sales")

<table class="table">
    <thead>
        <tr>
            <th>No</th>
            <th>Invoice No</th>
            <th>Date</th>
            <th>Customer</th>
            <th>Amount</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var receipt in Model.SalesReceiptListLines)
        {
            <tr>
                <td>@receipt.No</td>
                <td>@receipt.InvoiceNo</td>
                <td>@receipt.Date</td>
                <td>@receipt.CustomerName</td>
                <td>@receipt.AmountPaid</td>
            </tr>
        }
    </tbody>
</table>